spring:
  datasource:
    url:  jdbc:h2:tcp://localhost/~/jpa/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
  #      show_sql: true
        format_sql: true
        default_batch_fetch_size: 50

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
